server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://tmp-test.evaldofelipe.com:8080;

        proxy_set_header Host $host;

        # Keep these if you might proxy WebSocket connections
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400; # Adjust timeout as needed
    }
}
